# Generated by Django 5.2.2 on 2025-06-08 22:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('tutoria', 'Tutoría Académica'), ('clinica', 'Clínica de Aprendizaje'), ('psicopedagogia', 'Psicopedagogía'), ('orientacion', 'Orientación Estudiantil'), ('bienestar', 'Bienestar Estudiantil')], max_length=20)),
                ('contacto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('analista_cpa', 'Analista CPA'), ('coordinador_cpa', 'Coordinador CPA'), ('coordinador_carrera', 'Coordinador de Carrera')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('semestre', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('contamination_rate', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.5)])),
                ('n_estimators', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('umbral_promedio_min', models.FloatField(default=3.0)),
                ('umbral_asistencia_min', models.FloatField(default=70.0)),
                ('umbral_uso_plataforma_min', models.FloatField(default=60.0)),
                ('umbral_variacion_notas', models.FloatField(default=1.5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototipo.carrera')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeteccionAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anomalia', models.CharField(choices=[('bajo_rendimiento', 'Bajo Rendimiento'), ('baja_asistencia', 'Baja Asistencia'), ('alta_variabilidad', 'Alta Variabilidad'), ('uso_ineficiente_plataforma', 'Uso Ineficiente de Plataforma'), ('cambio_drastico_semestre', 'Cambio Drástico entre Semestres'), ('multiple', 'Múltiples Factores')], max_length=30)),
                ('score_anomalia', models.FloatField()),
                ('confianza', models.FloatField()),
                ('promedio_general', models.FloatField()),
                ('asistencia_promedio', models.FloatField()),
                ('uso_plataforma_promedio', models.FloatField()),
                ('variacion_notas', models.FloatField()),
                ('estado', models.CharField(choices=[('detectado', 'Detectado'), ('en_revision', 'En Revisión'), ('intervencion_activa', 'Intervención Activa'), ('resuelto', 'Resuelto'), ('falso_positivo', 'Falso Positivo')], default='detectado', max_length=20)),
                ('prioridad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_deteccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('criterio_usado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototipo.criterioanomalia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_deteccion', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='AlertaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_anomalia', 'Nueva Anomalía Detectada'), ('anomalia_critica', 'Anomalía Crítica'), ('asignatura_critica', 'Asignatura con Múltiples Anomalías'), ('seguimiento_vencido', 'Seguimiento Vencido')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('destinatarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('asignatura_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototipo.asignatura')),
                ('deteccion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototipo.deteccionanomalia')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_estudiantes_analizados', models.IntegerField()),
                ('anomalias_detectadas', models.IntegerField()),
                ('porcentaje_anomalias', models.FloatField()),
                ('parametros_modelo', models.JSONField()),
                ('metricas_modelo', models.JSONField()),
                ('tiempo_ejecucion', models.FloatField()),
                ('exitoso', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('criterio_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.criterioanomalia')),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ingreso_año', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='deteccionanomalia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.estudiante'),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('recibida', 'Recibida por Instancia'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('motivo', models.TextField()),
                ('observaciones_derivacion', models.TextField(blank=True)),
                ('respuesta_instancia', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('derivado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deteccion_anomalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.deteccionanomalia')),
                ('instancia_apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.instanciaapoyo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaCritica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_analizado', models.CharField(max_length=10)),
                ('total_estudiantes', models.IntegerField()),
                ('estudiantes_anomalos', models.IntegerField()),
                ('porcentaje_anomalias', models.FloatField()),
                ('promedio_general_asignatura', models.FloatField()),
                ('asistencia_promedio_asignatura', models.FloatField()),
                ('uso_plataforma_promedio', models.FloatField()),
                ('fecha_analisis', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.asignatura')),
            ],
            options={
                'ordering': ['-porcentaje_anomalias'],
                'unique_together': {('asignatura', 'semestre_analizado')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('nota2', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('nota3', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('nota4', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)])),
                ('promedio_notas', models.FloatField()),
                ('porcentaje_asistencia', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje_uso_plataforma', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura')},
            },
        ),
    ]
