# Generated by Django 5.2.2 on 2025-07-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='observaciones_seguimiento',
            field=models.TextField(blank=True, help_text='Observaciones y seguimiento de la derivación'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Crítica')], default=2, help_text='Prioridad específica de la derivación'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototipo.carrera'),
        ),
    ]
