# Generated by Django 5.2.2 on 2025-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0002_derivacion_observaciones_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deteccionanomalia',
            options={'ordering': ['-fecha_deteccion'], 'verbose_name': 'Detección de Anomalía', 'verbose_name_plural': 'Detecciones de Anomalías'},
        ),
        migrations.AddField(
            model_name='deteccionanomalia',
            name='nivel_criticidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', help_text='Nivel de criticidad: baja, media o alta', max_length=10),
        ),
    ]
