# Generated by Django 5.2.2 on 2025-11-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0003_alter_deteccionanomalia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('analista_cpa', 'Analista CPA'), ('coordinador_cpa', 'Coordinador CPA'), ('coordinador_carrera', 'Coordinador de Carrera'), ('admin', 'Administrador')], max_length=20),
        ),
    ]
