# Generated by Django 5.2.2 on 2025-11-10 23:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohorteEstudiantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cohorte', models.IntegerField(choices=[(1, 'Cohorte 1 - Riesgo Crítico'), (2, 'Cohorte 2 - Riesgo Alto'), (3, 'Cohorte 3 - Riesgo Medio-Bajo')])),
                ('semestre_academico', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('acciones_recomendadas', models.JSONField(default=list)),
                ('umbral_min', models.FloatField()),
                ('umbral_max', models.FloatField()),
                ('color', models.CharField(default='#999999', max_length=7)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('porcentaje_total', models.FloatField(default=0.0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cohorte Estudiantil',
                'verbose_name_plural': 'Cohortes Estudiantiles',
                'ordering': ['numero_cohorte'],
                'unique_together': {('numero_cohorte', 'semestre_academico')},
            },
        ),
        migrations.CreateModel(
            name='PrediccionDesercion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_academico', models.IntegerField(help_text='Semestre en el que se realizó la predicción', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prediccion', models.CharField(choices=[('Dropout', 'Deserción'), ('Enrolled', 'Inscrito'), ('Graduate', 'Graduado')], max_length=10)),
                ('probabilidad_desercion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probabilidad_graduacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probabilidad_inscrito', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10)),
                ('cohorte', models.IntegerField(help_text='1=Crítico, 2=Alto, 3=Medio-Bajo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('promedio_notas', models.FloatField()),
                ('asistencia_promedio', models.FloatField()),
                ('uso_plataforma', models.FloatField()),
                ('materias_aprobadas', models.IntegerField()),
                ('materias_inscritas', models.IntegerField()),
                ('fecha_prediccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('modelo_version', models.CharField(default='v1.0', max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prototipo.estudiante')),
            ],
            options={
                'verbose_name': 'Predicción de Deserción',
                'verbose_name_plural': 'Predicciones de Deserción',
                'ordering': ['-fecha_prediccion', '-probabilidad_desercion'],
            },
        ),
        migrations.CreateModel(
            name='ComparacionIntervenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_probabilidad', models.FloatField()),
                ('cambio_cohorte', models.IntegerField()),
                ('clasificacion', models.CharField(choices=[('mejora_significativa', 'Mejora Significativa'), ('mejora_leve', 'Mejora Leve'), ('estable', 'Estable'), ('deterioro_leve', 'Deterioro Leve'), ('deterioro_significativo', 'Deterioro Significativo')], max_length=30)),
                ('intervencion_descripcion', models.TextField(blank=True)),
                ('tipo_intervencion', models.CharField(blank=True, max_length=100)),
                ('fecha_comparacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones', to='prototipo.estudiante')),
                ('prediccion_antes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_como_antes', to='prototipo.predicciondesercion')),
                ('prediccion_despues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_como_despues', to='prototipo.predicciondesercion')),
            ],
            options={
                'verbose_name': 'Comparación de Intervención',
                'verbose_name_plural': 'Comparaciones de Intervenciones',
                'ordering': ['-fecha_comparacion'],
            },
        ),
        migrations.CreateModel(
            name='AlertaPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('riesgo_critico', 'Riesgo Crítico Detectado'), ('deterioro_significativo', 'Deterioro Significativo'), ('cambio_cohorte', 'Cambio de Cohorte'), ('mejora_significativa', 'Mejora Significativa')], max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('accion_sugerida', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='prototipo.predicciondesercion')),
            ],
            options={
                'verbose_name': 'Alerta de Predicción',
                'verbose_name_plural': 'Alertas de Predicción',
                'ordering': ['-fecha_generacion', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_predicciones', models.JSONField(default=list, help_text='Lista de predicciones por semestre')),
                ('tendencia', models.CharField(choices=[('mejora_significativa', 'Mejora Significativa'), ('mejora_leve', 'Mejora Leve'), ('estable', 'Estable'), ('deterioro_leve', 'Deterioro Leve'), ('deterioro_significativo', 'Deterioro Significativo'), ('sin_datos_suficientes', 'Sin Datos Suficientes')], default='sin_datos_suficientes', max_length=30)),
                ('cambio_total_riesgo', models.FloatField(default=0.0)),
                ('ultimo_nivel_riesgo', models.CharField(blank=True, max_length=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('tiene_alertas_activas', models.BooleanField(default=False)),
                ('total_alertas', models.IntegerField(default=0)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='prototipo.estudiante')),
            ],
            options={
                'verbose_name': 'Seguimiento de Estudiante',
                'verbose_name_plural': 'Seguimientos de Estudiantes',
            },
        ),
        migrations.AddIndex(
            model_name='predicciondesercion',
            index=models.Index(fields=['estudiante', 'semestre_academico'], name='prototipo_p_estudia_3c75e3_idx'),
        ),
        migrations.AddIndex(
            model_name='predicciondesercion',
            index=models.Index(fields=['cohorte', 'nivel_riesgo'], name='prototipo_p_cohorte_aa64e4_idx'),
        ),
    ]
